const truths = [
    'I wrestled at a juvenile detention school',
    'I almost died by running into a rock trash can as a child',
    'I was about to be in Hong Kong during the riots and Coronavirus',
    'I won a State Championship in track while running the 4x400',
    'I hiked Kilimanjaro',
    'I got lost in a subway in France',
    'I was shaved nearly bald (Full Metal Jacket style)',
    'I am learning how to skateboard',
    'I was actually a TA for Google before I was an intern',
    'I nearly died when I ran my bike straight into a fence at full speed',
    'I worked at a mall aquarium',
    'I worked vaccuming buildings',
    'I had my only anxiety attack ever on an airplane',
    'I won a gift card for knowing all the words to Ice Ice Baby',
    'I am born in the year of the dragon',
    'I still like reading ridiculous \'group of teens save the world books\'',
    'I don\'t like the taste of soda',
    'I have lived in LA but still haven\'t met someone famous',
    'I trecked up 3,000 feet of ice unprepared because that\'s how it be',
    'I learned a language consisting of replacing all vowels with IG',
    'I was ranked 7th in the state of Colorado for goals scored my junior year',
    'I watched every episode of Avatar to write a paper my freshman year of college',
    'I still struggle to know the difference between left and right',
    'I actually like Country music',
    'I played football as a child',
    'I wore a \'flying monkey\' costume to my fifth grade music show',
    'I am partially convinced we are living in a simulation',
    'I am in a food injustice service org',
    'I am scuba diving certified',
    'I won a 5th grade D2 championship with a band of misfits',
    'I recieved 14 Varsity Letters in High School',
    'I performed standup comedy in my fifth grade talent show',
    'I was terrified of a children\'s book called the Mosely Bug',
    'My first crush was Sam from iCarly',
    'I would like to be a contestant on CBS Survivor'
]

const lies = [
    'I  was MVP of my baseball team freshman year',
    'I submitted a video that was breifly featured on The Tonght Show',
    'I worked at an amusement park for a while',
    'I worked on Obama\'s presidential campaign',
    'I have an archnemesis',
    'My dog is named after a contemporary philosopher',
    'I made up a language that completely excludes the letter \'e\'',
    'I am actually a decent cook',
    'I have never lost a game of UNO (ever)',
    'I held the highest score in smash hit iPhone game Crossy Road for two years',
    'I jumped out of a plane on a dare',
    'I am banned from a flower shop in Wyoming',
    'I am still up to date on all the new Percy Jackson books',
    'I was good friends with a contestant on The Bachelor',
    'I am really good at the Ukelele'
]